### ISSUE TITLE
Tracking: Traders & Barbarians

### ISSUE THREAD

**Issue by thisisrandy** [thisisrandy/catan-randomizer#2]
This issue is to track the progress of adding all scenarios from the Traders & Barbarians expansion.

- [x] The Fishermen of Catan
  - [x] Board spec
  - [x] Images
    - [x] Fish tiles
    - [x] Lake
  - [x] Inland terrain (the Lake)
    - [x] Logic
    - [x] Tests
   - [x] Fish tiles
     - [x] Display
     - [x] Shuffling
       - [x] Logic
       - [x] Tests
       - [x] Decouple fixed sea hex & fixed port/tile concepts
- [x] The Rivers of Catan
  - [x] Board spec
  - [x] River tile images
  - [x] Multiple number chits per tile (for 2 & 12)
    - [x] Logic
    - [x] Display
    - [x] Tests
- [x] The Caravans
  - [x] Board spec
  - [x] Oasis image
- [x] Barbarian Attack
  - [x] Board spec
  - [x] Castle hex image
- [x] Traders & Barbarians
  - [x] Board spec
  - [x] Castle/Quarry/Glassworks hex images
- [x] T & B Ultimate
  - [x] Orientation display property
  - [x] Number groups
    - [x] Logic
    - [x] Tests
  - [x] All map specs
- [x] Fishermen combinations
  - [x] With Rivers
  - [x] With Caravans
  - [x] With Barbarian Attack
  - [x] With Traders & Barbarians
  - [x] Explorers & Pirates
  - [x] Seafarers
